import type { Variant } from '../types';
import { DIFFICULTY_ORDER, type Difficulty } from './rate';

/**
 * Difficulty tiers advertised per variant. The list is *not* guaranteed to be
 * a prefix of `DIFFICULTY_ORDER` — tiers the generator/rater cannot reliably
 * hit on a given grid are descoped so they are not advertised to the player.
 *
 * Iteration 7 collapsed the eight-tier ladder down to six and re-profiled at
 * n=50 for tighter confidence intervals. The iteration-7 final snapshot
 * (`scripts/tier-distribution.summary.json`, generated 2026-04-29 by
 * TASK-021 with `--all-tiers --n=50`) revealed that two cells still fall
 * below the required `solvedRate ≥ 0.05` threshold after the tier collapse:
 *
 *   - classic:Master  solvedRate=0.04, sampleSize=50 → descoped (§11 contingency)
 *   - six:Medium      solvedRate=0.02, sampleSize=50 → descoped (§11 contingency)
 *
 * Both are filed as iteration-8 scope. Classic therefore ships five tiers
 * (`Easy / Medium / Hard / Expert / Nightmare`) and Six ships one (`Easy`).
 *
 * Sources:
 *   1. Iteration-7 final snapshot,
 *      `scripts/tier-distribution.summary.json` (generated by TASK-021 with
 *      `--all-tiers --n=50`; sampleSize 50 per cell, full
 *      `DIFFICULTY_ORDER × {classic, six, mini}` sweep). `solvedRate` is the
 *      load-bearing rate (rated as target tier AND `result.solved === true`);
 *      the production code path rejects unsolved ratings, so this is what
 *      advertised tiers must clear (≥ 0.05).
 *   2. Iteration-6 lever-2 sweep,
 *      `scripts/tier-distribution.lever2.summary.json` (generated 2026-04-29,
 *      sampleSize 20 per cell, 14 synthetic cells via
 *      `--clue-floor-override` exploring lower clueFloors for the
 *      previously-descoped Six and Mini tiers). Iteration 7 inherits its
 *      Six/Mini descope decisions from this sweep — the rater extension for
 *      small grids (review §5.2 path 2) is deferred to iteration 8.
 *
 * Lever-2 ranges explored under the iteration-6 eight-tier ladder, kept here
 * as historical record so iteration 8 knows what was already tried (former
 * `CLUE_BOUNDS` lower bounds in parentheses; the iteration-6 tier names map
 * to the iteration-7 ladder per requirements §4.1: old Expert → new Hard,
 * old Diabolical → new Expert, old Demonic → new Master):
 *   - six.Medium             (was 18) — floors 14, 16
 *   - six.Hard       (old)   (was 15) — floors 11, 13
 *   - six.Expert     (old)   (was 12) — floors 8, 10
 *   - six.Master     (old)   (was 13) — floors 9, 11
 *   - six.Diabolical (old)   (was 11) — floors 7, 9
 *   - mini.Medium            (was 10) — floors 6, 8
 *   - mini.Hard              (was  8) — floors 5, 7
 *
 * Lever-2 results: every tested floor returned solvedRate=0. No tier
 * rescues were made via lever-2 for Six or Mini. Both variants ship only
 * the tiers their rater can reliably reach at the five-tier ladder floor:
 *   - Six: Easy only (Medium descoped per §11 final-snapshot contingency)
 *   - Mini: Easy only (Medium/Hard unreachable at every tested clueFloor)
 */
const VARIANT_TIERS: Record<string, readonly Difficulty[]> = {
  classic: ['Easy', 'Medium', 'Hard', 'Expert', 'Nightmare'],
  six: ['Easy'],
  mini: ['Easy'],
};

/**
 * Difficulty tiers that should be shown for the given variant, in ascending
 * order. Returns the per-variant list above. Unknown variant ids fall back to
 * the full `DIFFICULTY_ORDER`.
 */
export function availableTiers(variant: Variant): readonly Difficulty[] {
  return VARIANT_TIERS[variant.id] ?? DIFFICULTY_ORDER;
}
