import type { Variant } from '../types';
import { DIFFICULTY_ORDER, type Difficulty } from './rate';

/**
 * Difficulty tiers advertised per variant. The list is *not* guaranteed to be
 * a prefix of `DIFFICULTY_ORDER` — tiers the generator/rater cannot reliably
 * hit on a given grid are descoped so they are not advertised to the player.
 *
 * Iteration 7 collapsed the eight-tier ladder down to six. The iteration-6
 * corrected baseline showed `classic:Hard` and `classic:Master` were
 * statistically empty: every technique tagged `Hard` (`pointing`,
 * `box-line-reduction`) co-occurs in real puzzles with a subset that bumps
 * the rating to Expert, and every technique tagged `Master` (`x-wing`,
 * `swordfish`, `jellyfish`) co-occurs with a wing that bumps the rating to
 * Diabolical. Folding the empty bands' technique members into the next tier
 * up — and renaming the resulting six tiers to `Easy / Medium / Hard /
 * Expert / Master / Nightmare` — produces a player-facing ramp that is
 * monotonic in name *and* difficulty, without reclassifying any actually-
 * occurring puzzle. Under that collapse, classic advertises all six tiers.
 *
 * Sources:
 *   1. Iteration-7 corrected baseline,
 *      `scripts/tier-distribution.summary.json` (generated by TASK-013 with
 *      `--all-tiers --n=50`; sampleSize 50 per cell, full
 *      `DIFFICULTY_ORDER × {classic, six, mini}` sweep). `solvedRate` is the
 *      load-bearing rate (rated as target tier AND `result.solved === true`);
 *      the production code path rejects unsolved ratings, so this is what
 *      advertised tiers must clear (≥ 0.05).
 *   2. Iteration-6 lever-2 sweep,
 *      `scripts/tier-distribution.lever2.summary.json` (generated 2026-04-29,
 *      sampleSize 20 per cell, 14 synthetic cells via
 *      `--clue-floor-override` exploring lower clueFloors for the
 *      previously-descoped Six and Mini tiers). Iteration 7 inherits its
 *      Six/Mini descope decisions from this sweep — the rater extension for
 *      small grids (review §5.2 path 2) is deferred to iteration 8, so Six
 *      still advertises `[Easy, Medium]` and Mini still advertises `[Easy]`.
 *
 * Restoration rule: any (variant, tier, floor) cell with
 * `solvedRate ≥ 0.05` in the lever-2 summary restores the tier in the
 * advertised list (and lowers `CLUE_BOUNDS[variant][tier][0]` to that
 * floor in `rate.ts`).
 *
 * Lever-2 ranges explored under the iteration-6 eight-tier ladder, kept here
 * as historical record so iteration 8 knows what was already tried (former
 * `CLUE_BOUNDS` lower bounds in parentheses; the iteration-6 tier names map
 * to the iteration-7 ladder per requirements §4.1: old Expert → new Hard,
 * old Diabolical → new Expert, old Demonic → new Master):
 *   - six.Medium             (was 18) — floors 14, 16
 *   - six.Hard       (old)   (was 15) — floors 11, 13
 *   - six.Expert     (old)   (was 12) — floors 8, 10
 *   - six.Master     (old)   (was 13) — floors 9, 11
 *   - six.Diabolical (old)   (was 11) — floors 7, 9
 *   - mini.Medium            (was 10) — floors 6, 8
 *   - mini.Hard              (was  8) — floors 5, 7
 *
 * Lever-2 restorations (variant, tier, floor, solvedRate, sampleSize):
 *   - (six, Medium, 14, 0.05, 20) — restored in iteration 6. clueFloor
 *     lowered from 18 to 14 in `rate.ts`. The corresponding per-tier budget
 *     in `TIER_BUDGETS.Medium` was widened per the §6 reliability formula
 *     on this cell; iteration 7 re-pins it against the n=50 baseline.
 *
 * Remaining descopes for Six and Mini (iteration 6 evidence; carried
 * forward into iteration 7 unchanged because the iteration-7 collapse only
 * touches classic). The lever-2 sweep at lower floors (per the ranges above)
 * did not rescue any of these — every tested floor returned solvedRate=0:
 *   - (six,  old Hard,       0, 20) — the 6×6 rater chain produces almost
 *   - (six,  old Expert,     0, 20)   exclusively Easy/Medium at every
 *   - (six,  old Master,     0, 20)   tested clueFloor; Hard+ patterns are
 *   - (six,  old Diabolical, 0, 20)   statistically unreachable on this grid.
 *   - (mini, Medium,         0, 20) — the 4×4 rater chain produces 100%
 *   - (mini, old Hard,       0, 20)   Easy at every tested clueFloor (5–12).
 */
const VARIANT_TIERS: Record<string, readonly Difficulty[]> = {
  classic: ['Easy', 'Medium', 'Hard', 'Expert', 'Master', 'Nightmare'],
  six: ['Easy', 'Medium'],
  mini: ['Easy'],
};

/**
 * Difficulty tiers that should be shown for the given variant, in ascending
 * order. Returns the per-variant list above. Unknown variant ids fall back to
 * the full `DIFFICULTY_ORDER`.
 */
export function availableTiers(variant: Variant): readonly Difficulty[] {
  return VARIANT_TIERS[variant.id] ?? DIFFICULTY_ORDER;
}
